"""End-to-end pipeline v2 — ACE-Step lego based, no voice cloning.

Pipeline:
    audio + japanese lyrics
    → Demucs (1st pass) → instrumental_orig.wav
    → DPO Gemma translation (with rejection sampling for syllable count)
    → ACE-Step v1.5 lego mode (src=input audio) → ace_full.wav
    → Demucs (2nd pass on ace_full.wav) → ace_vocals.wav
    → mix(ace_vocals + instrumental_orig, +6dB / -3dB) → final.wav

Yields ``(stage, pct_0_to_1, payload)`` per stage so the Gradio UI can
render a progress bar. Cached intermediates are reused on rerun.

The voice-cloning stage (HQ-SVC / Seed-VC / OpenVoice) was evaluated and
dropped: every option degraded vocal quality more than it added speaker
character. ACE-Step's default vocalist happened to match the test song's
singer reasonably well; for other songs the speaker may differ and that
limitation is acknowledged.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Iterator

import numpy as np

REPO = Path(__file__).resolve().parents[2]
# Container default: bind-mount the host's model directory at /app/models.
# Override via ACE_CKPT_DIR for local-host runs.
ACE_CKPT = os.environ.get("ACE_CKPT_DIR", "/app/models/ace-step-v1.5")
ACE_LEGO_INSTRUCTION = "Generate the vocals track based on the audio context:"
ACE_LEGO_CAPTION = (
    "Female English vocals following the melody of the source audio exactly, "
    "expressive J-pop performance, every English line sung at the same "
    "pitch and timing as the original Japanese vocal"
)
ACE_LEGO_STRENGTH = 0.45
# Reverted to the FINAL_v6dB.wav conditions: 2B turbo (acestep-v15-turbo) +
# audio_cover_strength=0.45. FINAL_v6dB was generated by ace_step_variants3.py
# M2_lego_full_str0.45 and confirmed to be the highest-quality output.
# XL turbo + str=0.28 produced "雰囲気だけ" singing and is no longer used.
ACE_LEGO_CONFIG = "acestep-v15-turbo"
ACE_LEGO_STEPS = 16

# Candidate sweep centred on the FINAL_v6dB.wav conditions
# (2B turbo, seed=42, str=0.45).
# 4-tuple: (mode, seed, strength, vocal_db)
#   vocal_db: src_audio に渡す日本語ボーカルの減衰量 (dB)。
#   0 = フル音源 (FINAL_v6dB と同条件), -6 = 半分の音量, -12 = 1/4 音量。
ACE_CANDIDATES = [
    # ★ FINAL_v6dB.wav と同条件 (アンカー、再現性確保)
    ("lego", 42, 0.45, 0),
    # ボーカル抑制で音素漏洩を抑える sweep
    ("lego", 42, 0.45, -6),
    ("lego", 42, 0.45, -12),
    ("lego", 42, 0.50, -6),
    ("lego", 42, 0.50, -12),
    ("lego", 42, 0.40, -6),
    # 別 seed × 0.45 × vocal -6 (再現不可問題への安全網)
    ("lego", 777, 0.45, -6),
    ("lego", 2718, 0.45, -6),
    ("lego", 99, 0.45, -12),
    ("lego", 1234, 0.45, -6),
]

# DPO 1-shot translation was user-preferred over rejection sampling (the
# rejsamp candidates introduced repeated lines and stray meta text). Keep
# this at 1 unless we re-introduce stricter candidate filtering.
REJSAMP_N = 1
DEFAULT_DPO_MODEL = os.environ.get("DPO_MODEL_PATH", "/app/models/gemma-dpo-final")


# ---------- helpers ----------------------------------------------------


def _en_syllables(text: str) -> int:
    return len(re.findall(r"[aeiouy]+", text.lower()))


def _hash_audio(audio_path: Path) -> str:
    return hashlib.sha1(audio_path.read_bytes()).hexdigest()[:16]


def _hash_text(text: str) -> str:
    return hashlib.sha1(text.encode("utf-8")).hexdigest()[:8]


def _clean_meta(text: str) -> str:
    """Strip LLM meta-commentary from a translation candidate."""
    cuts = ["How do you want", "I'm not sure", "Can you give", "Note:", "  /  /"]
    for c in cuts:
        idx = text.find(c)
        if idx >= 0:
            text = text[:idx]
    return text.strip()


# ---------- stage functions -------------------------------------------


def _build_attenuated_src(
    full_audio: Path,
    vocals: Path,
    instrumental: Path,
    out_path: Path,
    vocal_db: float,
) -> Path:
    """日本語ボーカルを vocal_db だけ減衰させて instrumental と再合成した wav を作る。

    vocal_db == 0 の場合は full_audio をそのまま out_path にコピーする (FINAL_v6dB と同条件)。
    キャッシュ済み (out_path 存在時) は再生成しない。
    """
    if out_path.exists():
        return out_path
    if vocal_db == 0:
        shutil.copy2(str(full_audio), str(out_path))
        return out_path
    from src.pipeline.mix import mix_tracks_with_vocal_compression

    out_path.parent.mkdir(parents=True, exist_ok=True)
    mix_tracks_with_vocal_compression(
        vocals, instrumental, out_path,
        vocal_gain_db=vocal_db, inst_gain_db=0,
    )
    return out_path


def _stage_separate(audio_path: Path, out_dir: Path) -> tuple[Path, Path]:
    """Return ``(vocals, instrumental)``. Reuses if both wavs exist."""
    vocals = out_dir / "vocals.wav"
    inst = out_dir / "instrumental.wav"
    if vocals.exists() and inst.exists():
        return vocals, inst
    from src.separation.demucs_runner import separate

    out = separate(audio_path, out_dir)
    return out["vocals"], out["instrumental"]


def _stage_translate(
    lyrics_text: str,
    model_path: str,
    out_path: Path,
):
    """Generator yielding per-line + final translation events.

    Yields tuples ``(event_type, payload)``:
        ``("line", {idx, total, japanese, mora_count, english})`` — once per line
        ``("result", list_of_cleaned_dicts)`` — final list after sanitization

    The cleaned/sanitized result is what gets cached to disk. The per-line
    events use lightly-cleaned raw text so the UI can display them live
    before the final sanitization pass runs.
    """
    if out_path.exists():
        cached = json.loads(out_path.read_text("utf-8"))
        # Even for cached translations, replay them as line events so the
        # frontend's streaming UI behaves the same way.
        for idx, row in enumerate(cached):
            yield "line", {
                "idx": idx,
                "total": len(cached),
                "japanese": row.get("japanese", ""),
                "mora_count": row.get("mora_count", 0),
                "english": row.get("english", ""),
            }
        yield "result", cached
        return

    import torch

    from src.translator.lyrics_translator import LyricsTranslator
    from src.translator.sanitize import parse_translation

    torch.manual_seed(42)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(42)

    print(f"[translate] Loading DPO model from {model_path}", flush=True)
    tr = LyricsTranslator(model_path=model_path)
    lyrics_lines = [ln.strip() for ln in lyrics_text.splitlines() if ln.strip()]
    total = len(lyrics_lines)
    print(f"[translate] Translating {total} lines", flush=True)

    raw: list[dict] = []
    for idx, result in enumerate(
        tr.translate_iter(lyrics_lines, max_new_tokens=60, temperature=0.5)
    ):
        raw.append(result)
        live_english = _clean_meta(result.get("english_translation", "")).strip()
        print(
            f"[translate] line {idx + 1}/{total}  mora={result['target_syllables']}  → {live_english[:80]}",
            flush=True,
        )
        yield "line", {
            "idx": idx,
            "total": total,
            "japanese": result["original_japanese"],
            "mora_count": result["target_syllables"],
            "english": live_english,
        }

    cleaned = parse_translation(raw, mora_counter=tr.count_mora)
    for row in cleaned:
        row["english"] = _clean_meta(row.get("english", ""))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(cleaned, ensure_ascii=False, indent=2), "utf-8")
    print(f"[translate] Done. Cached to {out_path}", flush=True)
    yield "result", cleaned


_WHISPER_MODEL = None


def _whisper_lyric_score(
    wav_path: Path, workspace: Path, target_words: set[str]
) -> tuple[float, str]:
    """Score a candidate by how many target lyric words Whisper recognizes in it.

    1. Demucs the candidate → vocals.wav (isolating the singing)
    2. Run Whisper-tiny.en on vocals.wav → transcription
    3. Compute fraction of target words that appear in the transcript

    Higher = more recognizable English singing of our target lyrics. Pure
    RMS coverage couldn't tell ``actual singing`` from ``babbling`` — Whisper
    can, because it only confidently transcribes when the audio sounds like
    real English.
    """
    import re

    import soundfile as sf
    from faster_whisper import WhisperModel

    from src.separation.demucs_runner import separate

    workspace.mkdir(parents=True, exist_ok=True)
    out = separate(wav_path, workspace)
    vocals_wav = out["vocals"]

    global _WHISPER_MODEL
    if _WHISPER_MODEL is None:
        _WHISPER_MODEL = WhisperModel("base.en", device="cuda", compute_type="float16")
    segments, _info = _WHISPER_MODEL.transcribe(
        str(vocals_wav),
        beam_size=1,
        language="en",
        vad_filter=True,
        no_speech_threshold=0.5,
    )
    transcript = " ".join(s.text for s in segments).lower()
    transcript_words = set(re.findall(r"[a-z']+", transcript))

    if not target_words:
        return 0.0, transcript
    overlap = len(target_words & transcript_words) / max(len(target_words), 1)

    # Quick sanity stats so we can read the candidate logs in flight.
    data, sr = sf.read(str(vocals_wav))
    if data.ndim == 2:
        data = data.mean(axis=1)
    dur = len(data) / sr
    return overlap, f"{transcript[:80]}... ({dur:.1f}s, {len(transcript_words)} unique words)"


def _stage_ace_generate(
    audio_path: Path,
    vocals: Path,
    instrumental: Path,
    translations: list[dict],
    out_dir: Path,
    *,
    ace_candidates: list[tuple[str, int, float, int]] | None = None,
    post_fx_enabled: bool = True,
    post_fx_consonant_boost_db: float = 2.5,
    post_fx_breath_level_db: float = -28.0,
):
    """Run candidates, yielding log events then a sentinel with the final result.

    Yields tuples ``(stage, pct_or_none, payload)``:
        ``("log", None, {"text": ..., "level": ...})`` — progress log lines
        ``("__result__", None, (picked_final_wav, picked_tag, all_candidates))``
            — final sentinel, must be captured by the caller

    ``all_candidates`` is a list of dicts ``{tag, final_wav, score, detail}``
    sorted by score (best first). The Gradio UI uses this list to surface
    every candidate to the user so they can pick by ear; the picked best is
    still copied to ``picked_final_wav`` for callers that want a single file.

    ``vocals`` and ``instrumental`` are the Demucs-separated tracks from
    ``audio_path``; ``instrumental`` doubles as ``inst_orig`` for the final mix.
    """
    def _log(text: str, level: str = "info"):
        return ("log", None, {"text": text, "level": level})

    final_out = out_dir / "final_picked.wav"
    manifest_path = out_dir / "candidates_manifest.json"
    if final_out.exists() and manifest_path.exists():
        manifest = json.loads(manifest_path.read_text("utf-8"))
        yield _log("ACE-Step results loaded from cache")
        yield ("__result__", None, (final_out, manifest[0]["tag"] if manifest else "cached", manifest))
        return

    os.environ.setdefault("ACESTEP_CHECKPOINTS_DIR", ACE_CKPT)
    # IMPORTANT: do *not* touch CUBLAS_WORKSPACE_CONFIG / cudnn flags.
    # scripts/ace_step_variants3.py (the source of the M2 / FINAL gold
    # standard) ran on the default cudnn settings (deterministic=False,
    # benchmark=True). Forcing determinism here selects a different kernel
    # and yields different output than M2. Let ACE-Step's internal
    # ``set_seeds(manual_seeds=[seed])`` handle reproducibility via
    # ``GenerationParams.seed``.

    from acestep.handler import AceStepHandler
    from acestep.inference import GenerationConfig, GenerationParams, generate_music
    from acestep.llm_inference import LLMHandler

    candidates_used = ace_candidates if ace_candidates is not None else ACE_CANDIDATES
    n = len(candidates_used)

    out_dir.mkdir(parents=True, exist_ok=True)
    lyrics_block = "\n".join(r["english"] for r in translations if r.get("english"))

    yield _log(f"Initializing ACE-Step DiT ({ACE_LEGO_CONFIG})...")
    dit = AceStepHandler()
    _, ok = dit.initialize_service(
        project_root=ACE_CKPT,
        config_path=ACE_LEGO_CONFIG,
        device="auto",
        offload_to_cpu=False,
    )
    if not ok:
        raise RuntimeError("ACE-Step DiT init failed")
    yield _log("ACE-Step DiT ready")

    yield _log("Initializing ACE-Step LLM (acestep-5Hz-lm-1.7B)...")
    llm = LLMHandler()
    _, ok = llm.initialize(
        checkpoint_dir=ACE_CKPT,
        lm_model_path="acestep-5Hz-lm-1.7B",
        backend="pt",
        device="auto",
        offload_to_cpu=False,
        dtype=None,
    )
    if not ok:
        raise RuntimeError("ACE-Step LM init failed")
    yield _log("ACE-Step LLM ready")

    target_words: set[str] = set()
    for r in translations:
        for w in re.findall(r"[a-zA-Z']+", r.get("english", "").lower()):
            if len(w) > 1:
                target_words.add(w)

    candidates_dir = out_dir / "candidates"
    candidates_dir.mkdir(exist_ok=True)
    config = GenerationConfig(batch_size=1, audio_format="wav")

    from src.pipeline.mix import mix_tracks
    from src.separation.demucs_runner import separate

    scores: list[tuple[float, str, int, float, float, Path, str]] = []  # (score, mode, seed, strength, vocal_db, final_wav, detail)

    # ---- Warmup ------------------------------------------------------
    # Empirically, an M1-replica warmup (lego, seed=42, str=0.40) produced
    # worse output than a generic warmup with a distinct seed. Stay with
    # a generic warmup whose RNG consumption doesn't shadow any real seed
    # in the candidate sweep. The function of warmup is only to put cudnn
    # kernel selection / lazy init in a steady state.
    warmup_dir = candidates_dir / "_warmup"
    warmup_dir.mkdir(exist_ok=True)
    warmup_marker = warmup_dir / ".done"
    if not warmup_marker.exists():
        yield _log("Running warmup pass (seed=987654) — this is discarded")
        try:
            warmup_params = GenerationParams(
                task_type="lego",
                thinking=False,
                caption=ACE_LEGO_CAPTION,
                lyrics=lyrics_block,
                src_audio=str(audio_path),
                instruction=ACE_LEGO_INSTRUCTION,
                audio_cover_strength=ACE_LEGO_STRENGTH,
                vocal_language="en",
                inference_steps=ACE_LEGO_STEPS,
                seed=987654,  # not in ACE_CANDIDATES
            )
            print("  [best-of-N] running generic warmup pass ...")
            _ = generate_music(dit, llm, warmup_params, config, save_dir=str(warmup_dir))
        except Exception as e:
            print(f"  [best-of-N] warmup failed (continuing anyway): {e}")
            yield _log(f"Warmup failed (continuing): {e}", level="warn")
        warmup_marker.touch()
        for f in warmup_dir.glob("*.wav"):
            try:
                f.unlink()
            except Exception:
                pass
        yield _log("Warmup complete")

    # 候補ループの前に、必要な vocal_db レベルだけまとめて事前生成
    attenuated_srcs: dict[float, Path] = {}
    src_dir = out_dir / "attenuated_srcs_v2_compressor"
    src_dir.mkdir(exist_ok=True)
    unique_vocal_dbs = sorted({c[3] for c in candidates_used})
    yield _log(f"Preparing attenuated src_audio for vocal_db levels: {unique_vocal_dbs}")
    for vdb in unique_vocal_dbs:
        if vdb == 0:
            attenuated_srcs[vdb] = audio_path  # フル音源そのまま
        else:
            attenuated_srcs[vdb] = _build_attenuated_src(
                audio_path, vocals, instrumental,
                src_dir / f"src_voc{vdb:+d}db.wav", vdb,
            )
            yield _log(f"  src_voc{vdb:+d}db.wav ready")

    for i, (mode, seed, strength, vocal_db) in enumerate(candidates_used):
        # Do not call torch.manual_seed / cuda.manual_seed_all here.
        # ACE-Step's GenerationParams(seed=...) flows into the internal
        # set_seeds() which uses its own torch.Generator instance —
        # external manual_seed only perturbs the global RNG state and
        # diverges output from variants3.py's behaviour.

        tag = f"{mode}_seed{seed}_str{strength:.2f}_voc{vocal_db:+d}db"
        src_audio_for_cand = str(attenuated_srcs[vocal_db])
        common_kwargs = dict(
            thinking=False,
            caption=ACE_LEGO_CAPTION,
            lyrics=lyrics_block,
            src_audio=src_audio_for_cand,
            audio_cover_strength=strength,
            vocal_language="en",
            inference_steps=ACE_LEGO_STEPS,
            seed=seed,
        )
        if mode == "lego":
            params = GenerationParams(
                task_type="lego",
                instruction=ACE_LEGO_INSTRUCTION,
                **common_kwargs,
            )
        else:
            params = GenerationParams(task_type="cover", **common_kwargs)

        per_dir = candidates_dir / tag
        per_dir.mkdir(exist_ok=True)
        cand_path = per_dir / "ace.wav"

        yield _log(f"[{i+1}/{n}] Generating {tag} (seed={seed}, str={strength}, voc{vocal_db:+d}db)...")
        t_cand = time.time()
        if not cand_path.exists():
            try:
                result = generate_music(dit, llm, params, config, save_dir=str(per_dir))
            except Exception as e:
                print(f"  [best-of-N] {tag} generation EXCEPTION: {e}")
                yield _log(f"[{i+1}/{n}] {tag} generation EXCEPTION: {e}", level="error")
                continue
            if not result.success or not result.audios:
                print(f"  [best-of-N] {tag} FAILED: {result.error}")
                yield _log(f"[{i+1}/{n}] {tag} FAILED: {result.error}", level="error")
                continue
            shutil.move(str(result.audios[0]["path"]), str(cand_path))
        dt_cand = time.time() - t_cand
        yield _log(f"[{i+1}/{n}] {tag} done in {dt_cand:.1f}s")

        # Score on the candidate's vocals via Demucs + Whisper.
        yield _log(f"[{i+1}/{n}] Demucs 2nd pass on candidate...")
        try:
            score, detail = _whisper_lyric_score(
                cand_path, per_dir / "demucs_score", target_words
            )
            yield _log(f"[{i+1}/{n}] Whisper scoring: word_overlap={score:.3f}")
        except Exception as e:
            print(f"  [best-of-N] {tag} score FAILED: {e}")
            yield _log(f"[{i+1}/{n}] Whisper scoring FAILED: {e}", level="warn")
            score, detail = -1.0, str(e)

        # Build the candidate-specific final wav for ranking parity.
        final_path = per_dir / "final.wav"
        try:
            if mode == "lego":
                # Re-Demucs to isolate vocals, then mix with original inst.
                demucs_dir = per_dir / "demucs_mix"
                demucs_out = separate(cand_path, demucs_dir)
                if post_fx_enabled:
                    from src.pipeline.post_fx import process_vocal
                    processed_vocal = per_dir / "vocal_postfx.wav"
                    process_vocal(
                        demucs_out["vocals"], processed_vocal,
                        consonant_boost_db=post_fx_consonant_boost_db,
                        breath_level_db=post_fx_breath_level_db,
                    )
                    yield _log(
                        f"[{i+1}/{n}] post_fx: consonant_boost={post_fx_consonant_boost_db}dB,"
                        f" breath_level={post_fx_breath_level_db}dBFS"
                    )
                    mix_tracks(processed_vocal, instrumental, final_path)
                else:
                    mix_tracks(demucs_out["vocals"], instrumental, final_path)
            else:
                # Cover already contains its own instrumental; use as-is.
                shutil.copy2(str(cand_path), str(final_path))
        except Exception as e:
            print(f"  [best-of-N] {tag} mixing FAILED: {e}")
            yield _log(f"[{i+1}/{n}] mixing FAILED: {e}", level="error")
            continue

        yield _log(f"[{i+1}/{n}] Final mix written to {final_path.name}")
        print(f"  [best-of-N] {tag:48s}  word_overlap={score:.3f}  {detail}")
        scores.append((score, mode, seed, strength, vocal_db, final_path, detail))

    if not scores:
        raise RuntimeError("ACE-Step produced no candidates")
    scores.sort(key=lambda t: t[0], reverse=True)
    best_score, best_mode, best_seed, best_strength, best_vocal_db, best_path, _ = scores[0]
    best_tag = f"{best_mode}_seed{best_seed}_str{best_strength:.2f}_voc{best_vocal_db:+d}db"
    print(f"  [best-of-N] PICKED {best_tag} word_overlap={best_score:.3f}")
    yield _log(f"PICKED: {best_tag} (score={best_score:.3f})")
    shutil.copy2(str(best_path), str(final_out))

    # Build the manifest of every successful candidate so the UI can show
    # the full list and let the user pick by ear.
    manifest = [
        {
            "tag": f"{mode}_seed{seed}_str{strength:.2f}_voc{vocal_db:+d}db",
            "mode": mode,
            "seed": int(seed),
            "strength": float(strength),
            "vocal_db": int(vocal_db),
            "score": float(score),
            "final_wav": str(final_path),
            "detail": detail,
        }
        for score, mode, seed, strength, vocal_db, final_path, detail in scores
    ]
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), "utf-8")
    yield ("__result__", None, (final_out, best_tag, manifest))


def _stage_extract_vocals(ace_wav: Path, out_dir: Path) -> Path:
    """Demucs the ACE-Step output to isolate its vocals track."""
    target = out_dir / "ace_vocals.wav"
    if target.exists():
        return target
    from src.separation.demucs_runner import separate

    out = separate(ace_wav, out_dir)
    shutil.move(str(out["vocals"]), str(target))
    # We don't need the AI instrumental — discard.
    try:
        Path(out["instrumental"]).unlink()
    except Exception:
        pass
    return target


def _stage_mix(ace_vocals: Path, inst_orig: Path, out_path: Path) -> Path:
    if out_path.exists():
        return out_path
    from src.pipeline.mix import mix_tracks

    return mix_tracks(ace_vocals, inst_orig, out_path)


# ---------- orchestrator ----------------------------------------------


def run(
    audio_path: Path,
    lyrics_text: str,
    cache_root: Path = Path("cache"),
    dpo_model_path: str = DEFAULT_DPO_MODEL,
    *,
    ace_candidates: list[tuple[str, int, float, int]] | None = None,
    post_fx_enabled: bool = True,
    post_fx_consonant_boost_db: float = 2.5,
    post_fx_breath_level_db: float = -28.0,
) -> Iterator[tuple[str, float, dict]]:
    """Drive the full pipeline, yielding ``(stage, pct, payload)`` events.

    Parameters
    ----------
    ace_candidates:
        Override the module-level ACE_CANDIDATES sweep.  Each element is a
        4-tuple ``(mode, seed, strength, vocal_db)``.  Pass ``None`` to use
        the module-level default (backward compat).
    post_fx_enabled:
        When True the post-FX chain (consonant enhancer + breath insertion)
        is applied to the vocal track before the final mix.
    post_fx_consonant_boost_db / post_fx_breath_level_db:
        Control parameters forwarded to ``process_vocal``.
    """
    def _log(text: str, level: str = "info"):
        return ("log", None, {"text": text, "level": level})

    audio_path = Path(audio_path)
    if not audio_path.exists():
        raise FileNotFoundError(audio_path)

    candidates_used = ace_candidates if ace_candidates is not None else ACE_CANDIDATES

    audio_key = _hash_audio(audio_path)
    lyrics_key = _hash_text(lyrics_text)
    # ACE-Step config and candidate sweep are baked into the lyrics-level cache
    # key so that changing ACE_LEGO_CONFIG, ACE_LEGO_STRENGTH, or the preset
    # automatically invalidates old ACE-Step results (Demucs/translation caches
    # are reused across presets that share the same audio+lyrics).
    postfx_tag = (
        f"postfx_v1_on_cb{post_fx_consonant_boost_db}_bl{post_fx_breath_level_db}"
        if post_fx_enabled else "postfx_off"
    )
    ace_key = _hash_text(
        f"{ACE_LEGO_CONFIG}:{ACE_LEGO_STRENGTH}:voc_compressor_v1:{postfx_tag}:"
        + ",".join(f"{c[0]}-{c[1]}-{c[2]:.2f}-{c[3]:+d}" for c in candidates_used)
    )
    audio_cache = cache_root / audio_key
    lyrics_cache = audio_cache / f"{lyrics_key}_{ace_key}"
    audio_cache.mkdir(parents=True, exist_ok=True)
    lyrics_cache.mkdir(parents=True, exist_ok=True)

    yield _log(
        f"Job started — audio={audio_path.name}, lyrics={len(lyrics_text)} chars"
    )
    yield _log(f"Cache key: lyrics_cache={lyrics_cache.name}")
    yield _log(
        f"Preset: candidates={len(candidates_used)}, post_fx={post_fx_enabled}"
    )

    yield ("separate", 0.05, {"msg": "Separating vocals and instrumental..."})
    yield _log("Demucs 1st pass: separating vocals and instrumental...")
    t0 = time.time()
    vocals, inst_orig = _stage_separate(audio_path, audio_cache)
    vocals_size = vocals.stat().st_size if vocals.exists() else 0
    inst_size = inst_orig.stat().st_size if inst_orig.exists() else 0
    yield _log(
        f"Demucs done: vocals.wav ({vocals_size} bytes), instrumental.wav ({inst_size} bytes)"
    )
    yield (
        "separate",
        0.15,
        {"instrumental": str(inst_orig), "elapsed": round(time.time() - t0, 1)},
    )

    yield ("translate", 0.20, {"msg": "Translating lyrics with DPO Gemma..."})
    yield _log(f"Loading DPO Gemma model from {dpo_model_path}...")
    t0 = time.time()
    translations: list[dict] = []
    _translate_model_logged = False
    for ev_type, payload in _stage_translate(
        lyrics_text, dpo_model_path, lyrics_cache / "translation.json"
    ):
        if ev_type == "line":
            if not _translate_model_logged:
                # First line means model has loaded and started generating
                jp_lines = [ln.strip() for ln in lyrics_text.splitlines() if ln.strip()]
                yield _log(f"DPO model loaded. Translating {len(jp_lines)} Japanese lines...")
                _translate_model_logged = True
            # Reserve 0.20–0.55 for translation; allocate proportionally per line.
            line_pct = 0.20 + 0.35 * (payload["idx"] + 1) / max(payload["total"], 1)
            yield ("translate_line", line_pct, payload)
        elif ev_type == "result":
            translations = payload

    yield _log("Translation complete")
    yield (
        "translate",
        0.55,
        {
            "rows": len(translations),
            "translations": translations,
            "elapsed": round(time.time() - t0, 1),
        },
    )

    yield (
        "ace_step",
        0.60,
        {"msg": "Generating ACE-Step lego + cover candidates and picking by Whisper..."},
    )
    t0 = time.time()

    # _stage_ace_generate is now a generator. Drain it, forwarding log events
    # and capturing the final __result__ sentinel.
    picked_final: Path | None = None
    picked_tag: str = ""
    candidates: list[dict] = []
    n_cands = len(candidates_used)
    cand_done = 0

    for stage_ev, pct_ev, payload_ev in _stage_ace_generate(
        audio_path, vocals, inst_orig, translations, lyrics_cache,
        ace_candidates=ace_candidates,
        post_fx_enabled=post_fx_enabled,
        post_fx_consonant_boost_db=post_fx_consonant_boost_db,
        post_fx_breath_level_db=post_fx_breath_level_db,
    ):
        if stage_ev == "__result__":
            # Sentinel: unpack and stop iterating
            picked_final, picked_tag, candidates = payload_ev
            break
        elif stage_ev == "log":
            # Forward log event as-is; also emit candidate_progress when we
            # detect the per-candidate "done in Xs" lines so the UI grid ticks.
            yield (stage_ev, pct_ev, payload_ev)
            text = payload_ev.get("text", "")
            if "] " in text and "done in " in text:
                cand_done += 1
                ace_pct = 0.60 + 0.35 * cand_done / max(n_cands, 1)
                yield ("candidate_progress", ace_pct, {"done": cand_done, "total": n_cands})
        else:
            yield (stage_ev, pct_ev, payload_ev)

    if picked_final is None:
        raise RuntimeError("ACE-Step generator did not yield __result__ sentinel")

    final = lyrics_cache / "final.wav"
    shutil.copy2(str(picked_final), str(final))
    total_dt = time.time() - t0
    yield _log(f"Final pipeline output: {final.name} ({final.stat().st_size} bytes)")
    yield _log(f"Total time: {total_dt:.1f}s")
    yield (
        "done",
        1.0,
        {
            "final": str(final),
            "translations": translations,
            "picked": picked_tag,
            "candidates": candidates,
            "elapsed": round(total_dt, 1),
        },
    )
